### ISSUE TITLE
Techemistry crashes the game but throws other mod issues in the crash report

### ISSUE THREAD

**Issue by oly2o6** [al132mc/techemistry#1]
Hard to explain, but when adding techemistry v9 to my modpack it crashed, i checked the crash logs and got a mystical agriculture error, i then disabled that and got a compatched storage error in the crash logs, and the cycle goes on, but removing techeemistry and re adding both of the above mods i was able to run it just fine
using forge .69
https://pastebin.com/RqCPzhn1
https://pastebin.com/aa0Svmiv

**Comment by ghost** [comment]
I'm.. totally at a loss with this one. I was able to replicate it just fine by downloading your modpack and tossing in Techemistry, but i've fiddled around for hours and haven't really gotten anywhere. I even tried effectively commenting out the entire mod and tossing that in instead, but I was still getting some crashes.

**Comment by MasterEnderman** [comment]
I have the same issue and looked through the logs. Here's what I found:
```
[14:15:54] [Client thread/ERROR]: Exception caught during firing event: No value present
	Index: 5
	Listeners:
		0: NORMAL
		1: ASM: class al132.techemistry.Techemistry$RegistryEvents onRecipeRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		2: ASM: class al132.techemistry.Techemistry$RegistryEvents onContainerRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		3: ASM: class al132.techemistry.Techemistry$RegistryEvents onTERegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		4: ASM: class al132.techemistry.Techemistry$RegistryEvents onBlocksRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		5: ASM: class al132.techemistry.Techemistry$RegistryEvents onItemsRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at al132.chemlib.chemistry.ChemicalStack.<init>(ChemicalStack.java:30)
	at al132.chemlib.chemistry.ChemicalStack.<init>(ChemicalStack.java:26)
	at al132.techemistry.Ref.initItems(Ref.java:200)
	at al132.techemistry.Techemistry$RegistryEvents.onItemsRegistry(Techemistry.java:120)
	at net.minecraftforge.eventbus.ASMEventHandler_1213_RegistryEvents_onItemsRegistry_Register.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2189/364921596.accept(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65)
	at java.util.function.Consumer$$Lambda$2148/2030216407.accept(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65)
	at java.util.function.Consumer$$Lambda$2148/2030216407.accept(Unknown Source)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:125)
	at net.minecraftforge.fml.ModList$$Lambda$5427/841699338.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:125)
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96)
	at net.minecraftforge.fml.ModList$$Lambda$2125/165290225.dispatchEvent(Unknown Source)
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71)
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:197)
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189)
	at net.minecraftforge.fml.ModLoader$$Lambda$5455/2062965577.accept(Unknown Source)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:964)
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2032/1286005349.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2033/1479238498.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:454)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$409/748523772.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

[14:15:54] [Client thread/ERROR]: Caught exception during event RegistryEvent.Register<minecraft:item> dispatch for modid techemistry
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_51]
	at al132.chemlib.chemistry.ChemicalStack.<init>(ChemicalStack.java:30) ~[?:1.14.4-11]
	at al132.chemlib.chemistry.ChemicalStack.<init>(ChemicalStack.java:26) ~[?:1.14.4-11]
	at al132.techemistry.Ref.initItems(Ref.java:200) ~[?:1.14.4-10]
	at al132.techemistry.Techemistry$RegistryEvents.onItemsRegistry(Techemistry.java:120) ~[?:1.14.4-10]
	at net.minecraftforge.eventbus.ASMEventHandler_1213_RegistryEvents_onItemsRegistry_Register.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) [?:28.1]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2189/364921596.accept(Unknown Source) [?:28.1]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2148/2030216407.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2148/2030216407.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:125) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$5427/841699338.accept(Unknown Source) [?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) [?:1.8.0_51]
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:125) [?:?]
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2125/165290225.dispatchEvent(Unknown Source) [?:?]
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) [?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:197) [?:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189) [?:?]
	at net.minecraftforge.fml.ModLoader$$Lambda$5455/2062965577.accept(Unknown Source) [?:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:964) [?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2032/1286005349.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2033/1479238498.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) [?:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:454) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.79.jar:28.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$409/748523772.call(Unknown Source) [forge-1.14.4-28.1.79.jar:28.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?]
```

**Comment by ghost** [comment]
I think a lot of these weird crashes should be fixed now, try updating to ~~Techemistry v11 & ChemLib v13~~ Techemistry v12 & Chemlib v14

**Comment by MasterEnderman** [comment]
Everything seems to work with the new versions.
